//= ./../../node_modules/jquery/dist/jquery.min.js
// ./../../node_modules/swiper/swiper-bundle.min.js
//= ./libs/js.cookie.js
//= ./libs/jquery.fancybox.min.js
//= ./libs/jquery.time-to.min.js


//= ./partials/equal-height.js
//= ./partials/main.js
//= ./partials/cookies.js
//= ./partials/services-section.js
//= ./partials/how-it-works.js
//= ./partials/rating-section.js
//= ./partials/why-crypto.js
//= ./partials/crypto-solution.js
//= ./partials/crypto-line.js
//= ./partials/team.js
//= ./partials/advisors.js
//= ./partials/documents.js
//= ./partials/partners.js
//= ./partials/faqs.js
//= ./partials/token-sale.js
//= ./partials/timer.js
//= ./partials/payments-map.js
//= ./partials/timeline.js
//= ./partials/node-types.js
//= ./partials/how-to-get.js
//= ./partials/footer-carousel.js
//= ./partials/footer-menu-dots.js
//= ./partials/applying-carousel.js
//= ./partials/records-carousel.js
//= ./partials/blog-carousel.js